# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: danvk/yarn-python36:0.0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            yarn

      - save_cache:
          paths:
            - ./venv
            - ~/.yarn
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "yarn.lock" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8
            nosetests
            yarn test
